### ISSUE TITLE
Compiled with Laz 3.4

### ISSUE THREAD

**Issue by PeterOnDrums** [olivluca/rackctls#1]
Demo App Compiled with Laz 3.4
[RackDemo.zip](https://github.com/user-attachments/files/16102067/RackDemo.zip)

**Comment by olivluca** [comment]
What is the issue?

**Comment by PeterOnDrums** [comment]
No issue.
The Demo App code just follows the actual rules of "New Project/Application".
Anchors, LCL-Scaling (Hi-DPI), ...

**Comment by olivluca** [comment]
So if is there no issue why did you open an issue? :wink:
